# Generated by Django 4.1.5 on 2023-04-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_crop_details_humidity_alter_crop_details_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_details',
            name='fertilizer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop_details',
            name='soil_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
